creation_rules:
  # Encrypt Terraform variable files with GCP KMS
  - path_regex: terraform/.*\.tfvars$
    gcp_kms: projects/mpc-pollution-331382/locations/global/keyRings/sops-keyring/cryptoKeys/sops-key

  # Encrypt any .env files
  - path_regex: \.env\.enc$
    gcp_kms: projects/mpc-pollution-331382/locations/global/keyRings/sops-keyring/cryptoKeys/sops-key
