version: 2

models:
  - name: lnd_pollutants
    description: "Pollutants data"
    columns:
      - name: item_code
        data_type: "int"
        description: "Pollutant code"
      - name: item_name
        data_type: "string"
        description: "Pollutant name. The pollutants registered in the database are: SO2, NO2, O3, CO, PM10, PM2.5"
      - name: unit_of_measurement
        data_type: "string"
        description: "Unit of measurement"
      - name: good
        data_type: "float"
        description: "Good value"
      - name: normal
        data_type: "float"
        description: "Normal value"
      - name: bad
        data_type: "float"
        description: "Bad value"
      - name: very_bad
  - name: lnd_measurements
    description: "Measurements data"
    columns:
      - name: measurement_datetime
        data_type: "datetime"
        description: "Measurement datetime"
      - name: station_code
        data_type: "int"
        description: "Station code"
      - name: latitude
        data_type: "float"
        description: "Latitude"
      - name: longitude
        data_type: "float"
        description: "Longitude"
      - name: so2_value
        data_type: "float"
        description: "SO2 value"
      - name: no2_value
        data_type: "float"
        description: "NO2 value"
      - name: o3_value
        data_type: "float"
        description: "O3 value"
      - name: co_value
        data_type: "float"
        description: "CO value"
      - name: pm10_value
        data_type: "float"
        description: "PM10 value"
      - name: pm2_5_value
        data_type: "float"
        description: "PM2.5 value"
  - name: lnd_instrument_data
    description: "Instrument data"
    columns:
      - name: measurement_datetime
        data_type: "datetime"
        description: "Measurement datetime"
      - name: station_code
        data_type: "int"
        description: "Station code"
      - name: item_code
        data_type: "int"
      - name: average_value
        data_type: "float"
        description: "Average value"
      - name: instrument_status
        data_type: "int"
        description: "Status of the measuring instrument when the sample was taken. Values: 0 (Normal), 1 (Need for calibration), 2 (Abnormal), 4 (Power cut off), 8 (Under repair), 9 (Abnormal data)"
